# Generated by Django 6.0.1 on 2026-01-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_items_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
